KareAjansi.MVC/Controllers/MankenSayfaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KareAjansi.MVC.Controllers
{
    //[Authorize]
    public class MankenSayfaController : Controller
    {
        public IActionResult Liste()
        {
            return View();
        }

        public IActionResult Detay()
        {
            return View();
        }

        public IActionResult Ekle()
        {
            return View();
        }

        public IActionResult Guncelle()
        {
            return View();
        }
    }
}

KareAjansi.MVC/Controllers/OrganizasyonMankenSayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace KareAjansi.MVC.Controllers
{
    public class OrganizasyonMankenSayfaController : Controller
    {
        public IActionResult OrganizasyonMankenListe()
        {
            return View();
        }

        public IActionResult OrganizasyonMankenEkle()
        {
            return View();
        }
    }
}

KareAjansi.MVC/Controllers/OrganizasyonSayfaController.cs
using Microsoft.AspNetCore.Mvc;

namespace KareAjansi.MVC.Controllers
{
    public class OrganizasyonSayfaController : Controller
    {
        public IActionResult OrganizasyonListe()
        {
            return View();
        }

        public IActionResult OrganizasyonEkle()
        {
            return View();
        }

        public IActionResult OrganizasyonGuncelle()
        {
            return View();
        }
    }
}

KareAjansi.MVC/Controllers/UserController.cs
using KareAjansi.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace KareAjansi.MVC.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager) 
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterVM register, List<string> roles)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser
                {
                    Email = register.Email,
                    UserName = register.Username
                };

                var result = await _userManager.CreateAsync(user,register.ConfirmPassword);
                if (result.Succeeded)
                {
                    if (roles.Count > 0)
                    {
                        foreach (var role in roles)
                        {
                            await _userManager.AddToRoleAsync(user, role);
                        }
                    }
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

        public IActionResult Index()
        {
            var viewModelUser = new UserVM
            {
                Users = _userManager.Users.ToList(),
                UserRoles = new Dictionary<string, List<string>>()
            };

            foreach (var user in viewModelUser.Users)
            {
                var userRole = _userManager.GetRolesAsync(user).Result;
                viewModelUser.UserRoles[user.Id] = userRole.ToList();
            }
            ViewBag.Roles = _roleManager.Roles.ToList();
            return View(viewModelUser);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    TempData["Result"] = "Kullanıcı başarıyla silindi.";
                }
                else
                {
                    TempData["Result"] = "Kullanıcı silinirken hata oluştu.";
                }
            }
            else
            {
                TempData["Result"] = "Kullanıcı bulunamadı.";
            }
            return RedirectToAction("Index");
        }
    }
}

KareAjansi.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KareAjansi.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KareAjansi.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KareAjansi.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MankenSayfa" asp-action="Liste">Manken Liste</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrganizasyonSayfa" asp-action="OrganizasyonListe">Organizasyon Liste</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrganizasyonMankenSayfa" asp-action="OrganizasyonMankenListe">OrganizasyonManken Liste</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="index">Kullanıcı Listesi</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">@User.Identity.Name</a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        @if (User.IsInRole("User"))
                                        {
                                            <li>
                                                <a asp-action="Liste" asp-controller="MankenSayfa"  class="dropdown-item"></a></li>
                                        }
                                        <li><a class="dropdown-item" href="#!">Profile</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a asp-controller="Home" asp-action="Logout" class="dropdown-item">Logout</a></li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a asp-controller="Home" asp-action="Login" class="nav-link">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Home" asp-action="Register" class="nav-link">Register</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KareAjansi.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>